### ISSUE TITLE
External text files on objects

### ISSUE THREAD

**Issue by Omikhleia** [doughsay/room.js#170]
This proposed change exposes a new Text() command in-game, similar to the Verb() command, and allowing to have text strings kept in a separate file.

I should have done it the other way round and created the issue first (for easier reminder when listing the 4.x features), but anyhow this refers to PR #169 -- If approved, this will also require a doc update #140

**Comment by doughsay** [comment]
#169 is merged, leaving this issue open until docs have been updated.

**Comment by Omikhleia** [comment]
Closed via #185
