### ISSUE TITLE
how do you add a new trait?

### ISSUE THREAD

**Issue by dhaveman** [doughsay/room.js#184]
how do you add a new trait? such as "lib.traits.attackable" for example?

**Comment by Omikhleia** [comment]
All world objects have an ``addTrait`` method. So you would first create your "lib.traits.attackable" object with the suitable methods and properties, and add it to some other object.

> **addTrait( ...WorldObject ) ⇒ Integer**
> 
> Adds traits to the object and returns the number of traits. Traits are what makes the object inherit properties and methods.
> 
>  Warning: it doesn't prevent from adding an already existing trait. Maybe it should, otherwise the object gets broken, with a 'duplicate parent'.
>

**Comment by Omikhleia** [comment]
By the way, maybe your question is how to create a new trait in the first place.  One possible way among others:
```javascript
lib.root.new('lib.traits.attackable') // Spawn new object
lib.traits.attackable.rmTrait(lib.root) // Detach from root, for the trait to be standalone
// Then add properties, functions and verbs to lib.traits.attackable
...
// Then add this trait to some object, e.g. here to the baker NPC in the standard demo
items.baker.addTrait(lib.traits.attackable)
```
This should be what you asked for — Let me know if I can close the question.

**Comment by dhaveman** [comment]
if i add a new folder/files under the traits folder of a world, where do i get it to recognize that trait? can you point me to where it reads in all the "built in" traits? thanks!

i guess my main question is can i add a trait by just adding files/folders in the right spot?

something like:
world/lib/traits/attackable/attackable.json and the respective verbs/listener functions

thanks for the response!

**Comment by dhaveman** [comment]
Sounds good to me, thanks for the clarification and feedback!
