### ISSUE TITLE
Consider using MongoDB to persist the database

### ISSUE THREAD

**Issue by doughsay** [doughsay/room.js#21]

**Comment by christhekeele** [comment]
Heh, don't think I full appreciated this at the time:

> Now my randomly walking mobs walk around and go through an exit which used to point at that room, but now points to this new object (which isn't a room). Now they're stuck inside it, because there's no "go" verb inside that object. (They continuously cause exceptions).

Little living NullPointerExceptions. Delightful.

**Comment by doughsay** [comment]
lol...  amazing.  Speaking of... 3.0 doesn't have cron yet, no scheduled events...
