### ISSUE TITLE
Update Node.js to 5.x (or 6.x nightly) and make .babelrc more specific

### ISSUE THREAD

**Issue by cmbankester** [doughsay/room.js#71]
Given that Node.js 5 has [substantial ES6 support](https://nodejs.org/en/docs/es6/), updating to 5.x would make it possible for Babel to have to transpile fewer features (viz. the features that are unsupported in Node.js 5.x).

For instance, here's a `.babelrc` I'm currently using for a single page application targeting only the latest browsers:

```json
{
  "plugins": [
    "transform-es2015-destructuring",
    "transform-es2015-modules-commonjs",
    "transform-es2015-parameters",
    "transform-es2015-unicode-regex"
  ]
}
```

which relies on the following npm packages:
```json
{
  ...
  "dependencies": {
    ...
    "babel-plugin-transform-es2015-destructuring": "6.x",
    "babel-plugin-transform-es2015-modules-commonjs": "6.x",
    "babel-plugin-transform-es2015-parameters": "6.x",
    "babel-plugin-transform-es2015-unicode-regex": "6.x",
    ...
    }
}
```

Converting it to transpiling only those features unsupported by Node.js should be pretty easy. Alternatively, if the unsupported ES6 features you're using are relatively minor / limited, you could ditch Babel altogether.

It's also worth noting that Node.js 6 *should* be dropping sometime in April with [V8 5.0](https://chromium.googlesource.com/v8/v8.git/+log/branch-heads/5.0), which has [amazing support for ES6 features](http://v8project.blogspot.com/2016/03/v8-release-50.html). Also, you can try out Node.js 6 right now from the [nightlies page](https://nodejs.org/download/nightly/)

Just something to chew on before jumping on the Babel bandwagon (not to discount the benefits of using Babel; it's certainly a useful tool that has (in the past) made development using ES6 pretty swell).

**Comment by cmbankester** [comment]
Perhaps a better demonstration of the level of feature-completeness of V8 5.0's ES6 support would be the latest Chrome in Kangax's [ES6 compat table](http://kangax.github.io/compat-table/es6/#chrome51).

**Comment by doughsay** [comment]
@cmbankester totally didn't even notice this issue here!  So, I just completely rewrote everything again... as I love to do... `master` is now completely ES6 (minus modules) running completely natively on node 6.0 master.  No babel needed!  If you're interested, come check out the server currently running here: http://crazyjustin.com/room.js/

Also, thanks for pointing me to the nightlies page, I had no idea that existed, and have been compiling it myself from master... derp.

I'm glad I'm off babel for the server at least, but babel is still playing an important role in the client: https://github.com/doughsay/room.js-client

**Comment by cmbankester** [comment]
@doughsay That's basically the same paradigm I've landed at lately as well (using only module transpilation on the server, transpiling extra stuff for the browser), with the exception that I do allow my browser `.babelrc` to be somewhat relaxed (I basically remove transpilation of the newest features to land in both Firefox and Chrome stable as they land).

I'm excited for the pending release of Node 6! Now if only they'd add ES2015 module support...

**Comment by doughsay** [comment]
Node 6.0.0 is out!  https://github.com/doughsay/room.js/commit/9a15d6bcfab2b92832de30faeeefbc232d072240 removes the need for a locally linked 6.0.0-pre binary.  Closing as done!
