### ISSUE TITLE
addTrait/addAlias do not check for duplicates

### ISSUE THREAD

**Issue by Omikhleia** [doughsay/room.js#83]
The .addTrait() and .addAlias() method do not prevent a duplicate entry to be inserted.
- For .addAlias(), that not causing any issue, so its pretty minor (and for the reminder, .rmAlias() does remove duplicates anyhow)
- For .addTrait(), it does cause an issue (duplicate parents), which is a bit less friendly to the programmers.

The fixes would be pretty easy, but I'm uncertain whether there could maybe have been any rationale keeping those duplicates in the first place?

**Comment by doughsay** [comment]
Is this still an issue?

**Comment by Omikhleia** [comment]
My take at it, now that I understand things better:
- For .addAlias(), we could keep it unchanged, it's more a matter of documentation (which currently states the facts right, so it's ok) than anything else. It saves us for filtering the array each time it's modified (which may happen in-game, e.g. I used that to enable "bottle" as an alias when an object is renamed from "bottle of xxx" to "empty bottle").
- For .addTrait(), there are other ways to get duplicate parents, I'd say from C3 linearization as I understand it, so a basic filtering would actually only filter out the most obvious case and not be sufficient in general. That might again be a matter of documentation, on the same grounds as taking care when destroying objects used as traits, rather than trying to really check if adding a new trait may cause a problem (e.g. linearizing the objects and checking against duplicates in the trait list).

In both cases, such filtering would have some performance drawback (albeit likely small, but everything we can save is always good), whereas correct code never needs it. Since the behavior is documented, maybe we can reject a change here, indeed.

**Comment by doughsay** [comment]
I think it's fine to leave things the way they are.  Duplicate aliases or traits don't really cause any issues, and filtering when adding just adds extra complexity to the code.
