### ISSUE TITLE
Command parser extension suggestions

### ISSUE THREAD

**Issue by Omikhleia** [doughsay/room.js#85]
Say we have several object going by the same name and same aliases, so no way for distinguishing them, e.g. let's clone a dozen of bottles of beer ;)
The look-up functions in *world-object-class-builder.js* will return **ambiguous**:
- "this" verbs will not be invoked (= no matching verb on ambiguous, obviously)
- Other invoked verbs with "any" will usually test against ambiguous in their dobj/iobj and display messages such as "I can't tell which bottle you meant."

Suggestion: 
I'd eventually like to tackle with this issue by supporting qualifiers:
- Some way to specify a qualifier indicating which item to check, e.g. (as seen on different MUD code bases) `get 2.bottle` or `get bottle 2`, specifying the index of the object (within the appropriate container)
- An "all" qualifier, e.g. `get all` and `get all bottle`

The latter would likely require a "many" keyword for verbs, in that case expanding to an array of items. 

"any" may have to remain anyway, since things such as `unlock chest with all key` might not be acceptable (depending on the game, so that's a user decision).

Or do you have any other idea in mind?

**Comment by doughsay** [comment]
I agree and you've implemented the first version of it, so closing this issue.
